name: easygizi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.1
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.3
  iconly: ^1.0.1
  intl: ^0.17.0
  lottie: ^1.2.2
  sliding_clipped_nav_bar: ^2.0.1+8
  widget_mask: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/images/timesnewroman.ttf
